default_stages: [commit, merge-commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -  id: trailing-whitespace
    -  id: check-yaml
    -  id: check-json
    -  id: check-toml
    -  id: end-of-file-fixer
    -  id: name-tests-test
       args: [--django]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -  id: pyupgrade
       args: [--py37-plus]
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black
      language: system
      args: [--line-length=79, --config=pyproject.toml]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    - id: mypy
      language: system
      exclude: tests|docs/
-   repo: local
    hooks:
    - id: tests
      name: pytests
      entry: pytest tests/
      language: system
      always_run: true
      files: '^tests/test_.*\.py'
